### ISSUE TITLE
SEO Plugin Crashes Entire FLarum

### ISSUE THREAD

**Issue by mikejones3** [v17development/flarum-seo#9] opened 2019-01-25 04:56 UTC
Not really sure how or why this happened, it was kind of out of the blue. One minute my flarum was working and the next it was not. 

When I visited my flarum one last time before bed an all white page loaded with just this text:

`Error booting Flarum: SQLSTATE[HY000] [2002] No such file or directory (SQL: select `value`, `key` from `settings`)`

When I looked at my Flarum log here is the error I got:

```
[2019-01-23 04:19:19] production.ERROR: Error: Call to a member function getAttribute() on null in /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Mana$
Stack trace:
#0 /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Managers/QADiscussion.php(59): V17Development\FlarumSeo\Managers\QADiscussion->createTags()
#1 /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Listeners/PageListener.php(143): V17Development\FlarumSeo\Managers\QADiscussion->__construct(Object($
#2 /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Listeners/PageListener.php(106): V17Development\FlarumSeo\Listeners\PageListener->determine()
#3 /var/www/seekadventure.net/vendor/flarum/core/src/Frontend/Frontend.php(65): V17Development\FlarumSeo\Listeners\PageListener->__invoke(Object(Flarum\Frontend\Docume$
#4 /var/www/seekadventure.net/vendor/flarum/core/src/Frontend/Frontend.php(57): Flarum\Frontend\Frontend->populate(Object(Flarum\Frontend\Document), Object(Zend\Diacto$
#5 /var/www/seekadventure.net/vendor/flarum/core/src/Frontend/Controller.php(34): Flarum\Frontend\Frontend->document(Object(Zend\Diactoros\ServerRequest))
#6 /var/www/seekadventure.net/vendor/flarum/core/src/Http/RouteHandlerFactory.php(40): Flarum\Frontend\Controller->handle(Object(Zend\Diactoros\ServerRequest))
#7 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Zend\Diactoro$
#8 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\DispatchRoute->process(Object(Zend\Diactoros\ServerReques$
#9 /var/www/seekadventure.net/vendor/reflar/stopforumspam/src/Middleware/RegisterMiddleware.php(75): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest$
#10 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Reflar\Stopforumspam\middleware\RegisterMiddleware->process(Object(Zend\Diactor$
#11 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(58): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerReques$
#12 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\ShareErrorsFromSession->process(Object(Zend\Diactoros\Se$
#13 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#14 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\SetLocale->process(Object(Zend\Diactoros\ServerRequest),$
#15 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(34): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerReque$
#16 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Zend\Diactoros\S$
#17 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#18 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\RememberFromCookie->process(Object(Zend\Diactoros\Server$
#19 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/StartSession.php(62): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#20 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\StartSession->process(Object(Zend\Diactoros\ServerReques$
#21 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(48): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#22 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\CollectGarbage->process(Object(Zend\Diactoros\ServerRequ$
#23 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(29): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#24 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\ParseJsonBody->process(Object(Zend\Diactoros\ServerReque$
#25 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Middleware/HandleErrorsWithView.php(67): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#26 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\HandleErrorsWithView->process(Object(Zend\Diactoros\Serv$
#27 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(91): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#28 /var/www/seekadventure.net/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerReq$
#29 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\RequestHandler->process(Object(Zend\Diactoros\ServerReque$
#30 /var/www/seekadventure.net/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerReq$
#31 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePathRouter->process(Object(Zend\Diactoros\ServerReque$
#32 /var/www/seekadventure.net/vendor/middlewares/base-path/src/BasePath.php(53): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#33 /var/www/seekadventure.net/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePath->process(Object(Zend\Diactoros\ServerRequest), O$
#34 /var/www/seekadventure.net/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diact$
#35 /var/www/seekadventure.net/vendor/flarum/core/src/Http/Server.php(46): Zend\HttpHandlerRunner\RequestHandlerRunner->run()
#36 /var/www/seekadventure.net/public/index.php(18): Flarum\Http\Server->listen()
#37 {main}
```

To fix the issue, I was able to navigate to www.myURL.net/admin and access my admin dashboard of my flarum. Based on the above error mentioning the SEO plugin I disabled the plugin and poof my website was reachable again.

**Comment by jaspervriends** [comment] 2019-02-05 22:37
Hi @mikejones3 

I actually cannot reproduce this problem on the development forum at the moment.

I will need the whole first sentence of ```[2019-01-23 04:19:19] production.ERROR: Error: Call to a member function getAttribute() on null in /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Mana$```. There is a part after the $-sign that points to the specific code line.

Could you look this up to me?

By the way, the error `Error booting Flarum: SQLSTATE[HY000] [2002] No such file or directory (SQL: select 'value', 'key' from 'settings')` sounds like as not a regular SQL error message. Maybe there was something with your MySQL server or the socket?

I've checked the web for some answers, I found the following:
- https://laracasts.com/discuss/channels/laravel/sqlstatehy000-2002-no-such-file-or-directory-sql-select-count#reply=304754
- https://stackoverflow.com/a/42280909
- https://stackoverflow.com/a/20733001

But that is just speculating for me right now if that is the problem

**Comment by jaspervriends** [comment] 2019-02-06 08:33
Hi @mikejones3 thanks for the copy! The thing is, the text should go on after the $-signs at the end. As you can see all the log lines stops after the $-sign

Is there any part that comes after the $-sign? Specific for the first line.

Like you can see:
```[2019-01-23 04:19:19] production.ERROR: Error: Call to a member function getAttribute() on null in /var/www/seekadventure.net/vendor/v17development/flarum-seo/src/Mana$```

I need the part after `(...)vendor/v17development/flarum-seo/src/Mana$` so I can see the line where that function got executed (as there are multiple code lines with the getAttribute function)

Thanks in advance!

**Comment by mikejones3** [comment] 2019-02-10 04:21
@jaspervriends  that was everything copied and pasted from the log file....

I just updated to your latest version, seems to be working at this time. I will monitor and report back!

**Comment by jaspervriends** [comment] 2019-02-10 13:11
@mikejones3 That is weird... Thanks for checking the logfile again.

I hope it works fine from now on. For now I will close the issue. I will reopen this if it happens again!

**Closed by jaspervriends** 2019-02-10 13:11 UTC
Labels: bug, waiting for response
